#! /bin/sh

# Copyright (C) 2020 Intel Corporation
# SPDX-License-Identifier: MIT

export FFFC_TEMP_ENV_PATH=$(mktemp /tmp/fffc_env.XXXXXX)
fffc_internal_crashtool $@
export FFFC_DEBUG_REPLAY=$(cat $FFFC_TEMP_ENV_PATH)
unset FFFC_TEMP_ENV_PATH
